---
# This role describes the partitioning of the lfs disk

- name: Set partition label
  parted: dev=/dev/sdb label=gpt

- name: Create partitions
  parted: dev=/dev/sdb partid={{ item.id }} fstype={{ item.type }} start={{ item.start }} end={{ item.end }}
  with_items:
    - { id: 1, type: 'ext2', start: '0', end: '32mb' }             # boot
    - { id: 2, type: 'linux-swap', start: '32mb', end: '1056mb' }  # swap
    - { id: 3, type: 'ext4', start: '1056mb', end: '-1' }          # root

- name: Create ext* filesystems
  filesystem: dev={{ item.dev }} fstype={{ item.type }}
  with_items:
    - { dev: '/dev/sdb1', type: 'ext2' }  # boot
    - { dev: '/dev/sdb3', type: 'ext4' }  # root

- name: Mount partitions
  mount: fstype={{ item.type }} name={{ item.path }} src={{ item.node }} passno=2 state=mounted
  with_items:
    - { node: '/dev/sdb3', path: "{{ LFS }}/", type: 'ext4' }       # root
    - { node: '/dev/sdb1', path: "{{ LFS }}/boot/", type: 'ext2' }  # boot

- name: Setup swap
  swap: dev=/dev/sdb2
