---
# this script builds the basic system software as described by lfs chapter 6

- name: Create virtual file system mountpoints
  file: path={{ item }} state=directory
  with_items:
    - "{{ LFS }}/dev"
    - "{{ LFS }}/proc"
    - "{{ LFS }}/sys"
    - "{{ LFS }}/run"

- name: Create /dev/console device node
  shell: creates={{ LFS }}/dev/console mknod -m 600 {{ LFS }}/dev/console c 5 1

- name: Create /dev/null device node
  shell: creates={{ LFS }}/dev/null mknod -m 666 {{ LFS }}/dev/null c 1 3

# the mount module can't handle rebinds. using command instead
- name: Bind /dev to /mnt/lfs/dev
  command: creates={{ LFS }}/dev/sda mount --bind /dev {{ LFS }}/dev

- name: Mount virtual file systems
  command: mount -t {{ item.fs }} {{ item.fs }} {{ item.node }} {{ item.opts }}
  register: result
  failed_when: false
  changed_when: false
  with_items:
    - { fs: 'devpts', node: "{{ LFS }}/dev/pts", opts: '-o gid=5,mode=620' }
    - { fs: 'proc', node: "{{ LFS }}/proc", opts: '' }
    - { fs: 'sysfs', node: "{{ LFS }}/sys", opts: '' }
    - { fs: 'tmpfs', node: "{{ LFS }}/run", opts: '' }

# the following does not work due to some awkwardness with test in the shell module.
# using the script module instead (below)
#- name: Test for $LFS/dev/shm symlink
#  shell: test -h {{ LFS }}/dev/shm && test ! -d {{LFS }}/$(readlink {{ LFS }}/dev/shm)
#  register: dev_shm_test
#  failed_when: false
#  changed_when: dev_shm_test.rc == 0
#
#- name: Create Directory honoring $LFS/dev/shm symlink
#  shell: mkdir -p {{LFS }}/$(readlink {{ LFS }}/dev/shm)
#  when: dev_shm_test|changed
- name: Test for $LFS/dev/shm symlink
  script: 06.02.shm_symlink.sh
  register: dev_shm_symlink
  changed_when: dev_shm_symlink.stdout.find("changed") == 1

# start with the chrooted chapter 6 scripts
# the behemoth header piece in each of these scripts handles chrooting and logs
- name: 06.05. Creating Directories
  script: 06.05.creating_directories.sh creates={{ LFS }}/root

- name: Install $LFS/etc/passwd
  copy: src={{ item }} dest={{ LFS }}/etc/{{ item }} owner=root group=root
  with_items:
    - passwd
    - group

- name: 06.06. Creating Essential Files and Symlinks
  script: 06.06.creating_files.sh creates={{ LFS }}/bin/pwd

- name: 06.07. Linux-3.13.3 API Headers
  script: 06.07.linux-3.13.3-api-headers.sh creates={{ LFS }}/usr/include/asm/a.out.h

- name: 06.08. Man-pages-3.59
  script: 06.08.man-pages-3.59.sh creates={{ LFS }}/usr/share/man/man3/printf.3

- name: 06.09. Glibc-2.19
  script: 06.09.glibc-2.19.sh creates={{ LFS }}/lib/ld-linux.so.2

- name: 06.10. Adjusting the Toolcain
  script: 06.10.toolchain.sh creates={{ LFS }}/tools/bin/ld-old

- name: 06.11. Zlib-1.2.8
  script: 06.11.zlib-1.2.8.sh creates={{ LFS }}/usr/lib/libz.so

- name: 06.12. File-5.17
  script: 06.12.file-5.17.sh creates={{ LFS }}/usr/bin/file

- name: 06.13. Binutils-2.24
  script: 06.13.binutils-2.24.sh creates={{ LFS }}/usr/bin/addr2line

- name: 06.14. GMP-5.1.3
  script: 06.14.gmp-5.1.3.sh creates={{ LFS }}/usr/lib/libgmp.so

- name: 06.15. MPFR-3.1.2
  script: 06.15.mpfr-3.1.2.sh creates={{ LFS }}/usr/lib/libmpfr.so

- name: 06.16. MPC-1.0.2
  script: 06.16.mpc-1.0.2.sh creates={{ LFS }}/usr/lib/libmpc.so

- name: 06.17. GCC-4.8.2
  script: 06.17.gcc-4.8.2.sh creates={{ LFS }}/usr/bin/gcc

- name: 06.18. Sed-4.2.2
  script: 06.18.sed-4.2.2.sh creates={{ LFS }}/bin/sed

- name: 06.19. Bzip2-1.0.6
  script: 06.19.bzip2-1.0.6.sh creates={{ LFS }}/bin/bzip2

- name: 06.20. Pkg-config-0.28
  script: 06.20.pkg-config-0.28.sh creates={{ LFS }}/usr/bin/pkg-config

- name: 06.21. Ncurses-5.9
  script: 06.21.ncurses-5.9.sh creates={{ LFS }}/usr/lib/libncursesw.so

- name: 06.22. Shadow-4.1.5.1
  script: 06.22.shadow-4.1.5.1.sh creates={{ LFS }}/bin/passwd

- name: 06.23. Psmisc-22.20
  script: 06.23.psmisc-22.20.sh creates={{ LFS }}/bin/killall

- name: 06.24. Procps-ng-3.3.9
  script: 06.24.procps-ng-3.3.9.sh creates={{ LFS }}/bin/pidof

- name: 06.25. E2fsprogs-1.42.9
  script: 06.25.e2fsprogs-1.42.9.sh creates={{ LFS }}/sbin/mkfs.ext3

- name: 06.26. Coreutils-8.22
  script: 06.26.coreutils-8.22.sh creates={{ LFS }}/bin/cp

- name: 06.27. Iana-Etc-2.30
  script: 06.27.iana-etc-2.30.sh creates={{ LFS }}/etc/protocols

- name: 06.28. M4-1.4.17
  script: 06.28.m4-1.4.17.sh creates={{ LFS }}/usr/bin/m4

- name: 06.29. Flex-2.5.38
  script: 06.29.flex-2.5.38.sh creates={{ LFS }}/usr/bin/flex

- name: 06.30. Bison-3.0.2
  script: 06.30.bison-3.0.2.sh creates={{ LFS }}/usr/bin/bison

- name: 06.31. Grep-2.16
  script: 06.31.grep-2.16.sh creates={{ LFS }}/bin/grep

- name: 06.32. Readline-6.2
  script: 06.32.readline-6.2.sh creates={{ LFS }}/usr/include/readline

- name: 06.33. Bash-4.2
  script: 06.33.bash-4.2.sh creates={{ LFS }}/usr/share/doc/bash-4.2

- name: 06.34. Bc-1.06.95
  script: 06.34.bc-1.06.95.sh creates={{ LFS }}/usr/bin/bc

- name: 06.35. Libtool-2.4.2
  script: 06.35.libtool-2.4.2.sh creates={{ LFS }}/usr/bin/libtool

- name: 06.36. GDBM-1.11
  script: 06.36.gdbm-1.11.sh creates={{ LFS }}/usr/lib/libgdbm.so

- name: 06.37. Inetutils-1.9.2
  script: 06.37.inetutils-1.9.2.sh creates={{ LFS }}/bin/ping

- name: 06.38. Perl-5.18.2
  script: 06.38.perl-5.18.2.sh creates={{ LFS }}/usr/bin/perl5.18.2

- name: 06.39. Autoconf-2.69
  script: 06.39.autoconf-2.69.sh creates={{ LFS }}/usr/bin/autoconf

- name: 06.40. Automake-1.14.1
  script: 06.40.automake-1.14.1.sh creates={{ LFS }}/usr/bin/automake

- name: 06.41. Diffutils-3.3
  script: 06.41.diffutils-3.3.sh creates={{ LFS }}/usr/bin/diff

- name: 06.42. Gawk-4.1.0
  script: 06.42.gawk-4.1.0.sh creates={{ LFS }}/usr/bin/gawk

- name: 06.43. Findutils-4.4.2
  script: 06.43.findutils-4.4.2.sh creates={{ LFS }}/bin/find

- name: 06.44. Gettext-0.18.3.2
  script: 06.44.gettext-0.18.3.2.sh creates={{ LFS }}/usr/bin/gettext

- name: 06.45. Groff-1.22.2
  script: 06.45.groff-1.22.2.sh creates={{ LFS }}/usr/bin/groff

- name: 06.46. Xz-5.0.5
  script: 06.46.xz-5.0.5.sh creates={{ LFS }}/bin/xz

- name: 06.47. GRUB-2.00
  script: 06.47.grub-2.00.sh creates={{ LFS }}/sbin/grub-install

- name: 06.48. Less-458
  script: 06.48.less-458.sh creates={{ LFS }}/usr/bin/less

- name: 06.49. Gzip-1.6
  script: 06.49.gzip-1.6.sh creates={{ LFS }}/bin/gzip

- name: 06.50. IPRoute2-3.12.0
  script: 06.50.iproute2-3.12.0.sh creates={{ LFS }}/etc/iproute2

- name: 06.51Kbd-2.0.1
  script: 06.51.kbd-2.0.1.sh creates={{ LFS }}/usr/bin/dumpkeys

- name: 06.52. Kmod-16
  script: 06.52.kmod-16.sh creates={{ LFS }}/bin/lsmod

- name: 06.53. Libpipeline-1.2.6
  script: 06.53.libpipeline-1.2.6.sh creates={{ LFS }}/usr/lib/libpipeline.so

- name: 06.54. Make-4.0
  script: 06.54.make-4.0.sh creates={{ LFS }}/usr/bin/make

- name: 06.55. Patch-2.7.1
  script: 06.55.patch-2.7.1.sh creates={{ LFS }}/usr/bin/patch

- name: 06.56. Sysklogd-1.5
  script: 06.56.sysklogd-1.5.sh creates={{ LFS }}/sbin/syslogd

- name: 06.57. Sysvinit-2.88dsf
  script: 06.57.sysvinit-2.88dsf.sh creates={{ LFS }}/sbin/init

- name: 06.58. Tar-1.27.1
  script: 06.58.tar-1.27.1.sh creates={{ LFS }}/bin/tar

- name: 06.59. Texinfo-5.2
  script: 06.59.texinfo-5.2.sh creates={{ LFS }}/usr/share/texinfo

- name: 06.60. Udev-208
  script: 06.60.udev-208.sh creates={{ LFS }}/sbin/udevadm

- name: 06.61. Util-linux-2.24.1
  script: 06.61.util-linux-2.24.1.sh creates={{ LFS }}/sbin/swapon

- name: 06.62. Man-DB-2.6.6
  script: 06.62.man-db-2.6.6.sh creates={{ LFS }}/usr/bin/man

- name: 06.63. Vim-7.4
  script: 06.63.vim-7.4.sh creates={{ LFS }}/usr/bin/vim
  register: build

- name: 06.65. Stripping
  script: 06.65.stripping.sh
  when: build|changed

- name: 06.66. Cleaning Up
  script: 06.66.cleanup.sh
  when: build|changed
