---
# This role describes the lfs build requirements to the host system

- name: Create lfs tools directory
  file: path={{ LFS }}/tools/ state=directory
  register: tools_directory

- name: Create lfs tools symlink in /
  file: src={{ LFS }}/tools/ dest=/tools state=link

- name: Create the lfs group
  group: name=lfs

- name: Create the lfs user
  user: name=lfs group=lfs groups=admin shell=/bin/bash skel=/dev/null

- name: Create .ssh directory for the lfs user
  file: owner=lfs group=lfs path=/home/lfs/.ssh state=directory mode=0700

- name: Create authorized keys for the lfs user
  copy: owner=lfs group=lfs src=files/authorized_keys dest=/home/lfs/.ssh/authorized_keys mode=0600

- name: Install bash profile of the lfs user
  copy: src={{ item }} dest=/home/lfs owner=lfs group=lfs
  with_items:
    - ".bash_profile"
    - ".bashrc"

- name: Change ownership of LFS directories
  file: path={{ item }} owner=lfs
  with_items:
    - "{{ LFS }}/tools/"
    - "{{ LFS }}/sources/"
