---
# this sets up the prerequesites for lfs bootstrapping in the virtual machine

- name: Add GNU backport PPA
  apt_repository: repo=ppa:dns/gnu

- name: Update the server
  apt: update_cache=yes upgrade=full cache_valid_time=172800

- name: Install package dependencies
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - bash
    - binutils
    - bison
    - bzip2
    - coreutils
    - diffutils
    - findutils
    - gawk
    - gcc
    - g++
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - libc6-dev
    - gzip
    - m4
    - make
    - patch
    - perl
    - sed
    - tar
    - xz-utils

- name: Update program symlinks
  alternatives: name={{ item.name }} link={{ item.link }} path={{ item.path }}
  with_items:
    - { name: 'sh', link: '/bin/sh', path: '/bin/bash' }
    - { name: 'yacc', link: '/usr/bin/yacc', path: '/usr/bin/bison' }
    - { name: 'awk', link: '/usr/bin/awk', path: '/usr/bin/gawk' }

# kernel updates, and required reboots seems to break vagrant integration.
#- name: Install Linux Kernel >= 2.6.32
#  apt: name=linux-image-generic state=latest
#  register: kernel
#
#- name: Install Linux Kernel Headers >= 2.6.32
#  apt: name=linux-headers-generic state=latest
#
#- name: Restart machine if kernel changed
#  shell: reboot &
#  when: kernel|changed
#
#- name: Wait until down
#  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} state=stopped
#  when: kernel|changed
#
#- name: Wait until up
#  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=2
#  when: kernel|changed

