---
# This role installs required host packages

- name: Install package dependencies
  pacman: name={{ item }} state=present
  with_items: packages

- name: Update program symlinks
  file: path={{ item.path }} src={{ item.src }} state=link
  with_items: symlinks

