---
# this script describes the paackaging layout as required by lfs in chapter 3

- name: Create sources directory
  file: path={{ LFS }}/sources state=directory

- name: Fetch LFS wget-list and md5sums
  get_url: dest={{ LFS }}/sources/ url={{ item }}
  with_items:
    - "http://www.linuxfromscratch.org/lfs/downloads/{{ VERS }}/wget-list"
    - "http://www.linuxfromscratch.org/lfs/downloads/{{ VERS }}/md5sums"

# check if packages are present, and fetch them if necessary
- name: Validate LFS package checksums
  command: chdir={{ LFS }}/sources md5sum -c --quiet --strict {{ LFS }}/sources/md5sums
  register: md5_result
  changed_when: md5_result.rc != 0
  failed_when: false

- name: Fetch LFS packages
  command: wget -Nqi {{ LFS }}/sources/wget-list -P {{ LFS }}/sources
  when: md5_result|changed

