---
# this role describes the source packages used during the lfs build

- name: Create sources directory
  file: path={{ LFS }}/sources state=directory

- name: Fetch LFS wget-list and md5sums
  get_url: dest={{ LFS }}/sources/ url={{ item }}
  with_items:
    - "http://www.linuxfromscratch.org/lfs/downloads/{{ VERS }}/wget-list"
    - "http://www.linuxfromscratch.org/lfs/downloads/{{ VERS }}/md5sums"

- name: Fetch LFS packages
  wget: files={{ LFS }}/sources/wget-list md5sums={{ LFS }}/sources/md5sums
