---
# variables required for prerequesites

# list of packages required on the virtual host:
packages:
  - build-essential
  - bash
  - binutils
  - bison
  - bzip2
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gcc
  - g++
  - libgmp-dev
  - libmpfr-dev
  - libmpc-dev
  - libc6-dev
  - gzip
  - m4
  - make
  - patch
  - perl
  - sed
  - tar
  - xz-utils

# list of required symlinks:
symlinks:
  - { name: 'sh', link: '/bin/sh', path: '/bin/bash' }
  - { name: 'yacc', link: '/usr/bin/yacc', path: '/usr/bin/bison' }
  - { name: 'awk', link: '/usr/bin/awk', path: '/usr/bin/gawk' }
