---
# variables required for prerequesites

# list of packages required on the virtual host:
packages:
  - bash
  - binutils
  - bison
  - bzip2
  - coreutils
  - diffutils
  - findutils
  - gawk
  - gcc
  - glibc
  - grep
  - gzip
  - linux
  - linux-headers
  - m4
  - make
  - patch
  - perl
  - sed
  - tar
  - xz

# list of required symlinks:
symlinks:
  - { path: '/bin/sh', src: '/bin/bash' }
  - { path: '/usr/bin/awk', src: '/usr/bin/gawk' }
