---
# this script sets up the partition required by and described in lfs chapter 2

- name: Create LFS mount points
  file: path={{ item }} state=directory
  with_items:
    - "{{ LFS }}/"
    - "{{ LFS }}/boot/"

- name: Set partition label
  shell: creates=/dev/sdb1 parted -s -- /dev/sdb mklabel gpt
  register: partitioning

- name: Create partitions
  shell: parted -s -- /dev/sdb mkpart primary {{ item.type }} {{ item.start }} {{ item.end }}
  when: partitioning|changed
  with_items:
    - { type: 'ext2', start: '0', end: '32mb' } # boot
    - { type: 'linux-swap', start: '32mb', end: '1056mb' } # swap
    - { type: 'ext4', start: '1056mb', end: '-1' } # root

- name: Create ext* filesystems
  filesystem: dev={{ item.node }} fstype={{ item.type }}
  with_items:
    - { node: '/dev/sdb1', type: 'ext2' } # boot
    - { node: '/dev/sdb3', type: 'ext4' } # root

- name: Mount partitions
  mount: fstype={{ item.type }} name={{ item.path }} src={{ item.node }} passno=2 state=mounted
  with_items:
    - { node: '/dev/sdb3', path: "{{ LFS }}/", type: 'ext4' } # root
    - { node: '/dev/sdb1', path: "{{ LFS }}/boot/", type: 'ext2' } # boot

- name: Create swap space
  shell: mkswap /dev/sdb2
  when: partitioning|changed

- name: Enable swapping
  shell: swapon /dev/sdb2
  when: partitioning|changed

- name: Add swap entry to /etc/fstab
  shell: echo "/dev/sdb2 none swap sw 0 0" >> /etc/fstab
  when: partitioning|changed

